Introduction of the Pure attribute
CptWesley/BackwardsCompatibleFeatures pull request #1
Opened 2023-06-09 19:39 UTC by Corniel

The `[Pure]` attribute has been introduced in .NET framework 4.0. 

See: https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.contracts.pureattribute

2023-06-10 08:13 UTC, CptWesley requested changes

2023-06-10 08:13 UTC, CptWesley commented on src/BackwardsCompatibleFeatures/PureAttribute.cs
> +﻿#if !NET40_OR_GREATER && !NETSTANDARD1_0_OR_GREATER && !NETCOREAPP1_0_OR_GREATER
`!NETSTANDARD1_0_OR_GREATER` should be `!NETSTANDARD2_0_OR_GREATER`, since the attribute was only introduced in netstandard2.0

2023-06-10 18:18 UTC, Corniel commented on src/BackwardsCompatibleFeatures/PureAttribute.cs
> +﻿#if !NET40_OR_GREATER && !NETSTANDARD1_0_OR_GREATER && !NETCOREAPP1_0_OR_GREATER
Yeah. Me bad. I do not have all SDK's locally, so it's more challenging to get things straight.

2023-06-10 19:49 UTC, CptWesley approved these changes

2023-06-10 19:49 UTC, merged

2023-06-10 20:58 UTC, Corniel commented
No release?

2023-06-11 06:25 UTC, CptWesley commented
> No release?

Published now as 2.3.0

Releases are not automated